# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmac/Documents/projects2025/opengl-template-ibo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmac/Documents/projects2025/opengl-template-ibo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmac/Documents/projects2025/opengl-template-ibo/CMakeFiles /home/dmac/Documents/projects2025/opengl-template-ibo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmac/Documents/projects2025/opengl-template-ibo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

EBO.o: EBO.cpp.o
.PHONY : EBO.o

# target to build an object file
EBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EBO.cpp.o
.PHONY : EBO.cpp.o

EBO.i: EBO.cpp.i
.PHONY : EBO.i

# target to preprocess a source file
EBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EBO.cpp.i
.PHONY : EBO.cpp.i

EBO.s: EBO.cpp.s
.PHONY : EBO.s

# target to generate assembly for a file
EBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/EBO.cpp.s
.PHONY : EBO.cpp.s

IBO.o: IBO.cpp.o
.PHONY : IBO.o

# target to build an object file
IBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/IBO.cpp.o
.PHONY : IBO.cpp.o

IBO.i: IBO.cpp.i
.PHONY : IBO.i

# target to preprocess a source file
IBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/IBO.cpp.i
.PHONY : IBO.cpp.i

IBO.s: IBO.cpp.s
.PHONY : IBO.s

# target to generate assembly for a file
IBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/IBO.cpp.s
.PHONY : IBO.cpp.s

Mesh.o: Mesh.cpp.o
.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i
.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s
.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

ModelLoader.o: ModelLoader.cpp.o
.PHONY : ModelLoader.o

# target to build an object file
ModelLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ModelLoader.cpp.o
.PHONY : ModelLoader.cpp.o

ModelLoader.i: ModelLoader.cpp.i
.PHONY : ModelLoader.i

# target to preprocess a source file
ModelLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ModelLoader.cpp.i
.PHONY : ModelLoader.cpp.i

ModelLoader.s: ModelLoader.cpp.s
.PHONY : ModelLoader.s

# target to generate assembly for a file
ModelLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ModelLoader.cpp.s
.PHONY : ModelLoader.cpp.s

Scene.o: Scene.cpp.o
.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i
.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s
.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

Texture.o: Texture.cpp.o
.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i
.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s
.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

VAO.o: VAO.cpp.o
.PHONY : VAO.o

# target to build an object file
VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/VAO.cpp.o
.PHONY : VAO.cpp.o

VAO.i: VAO.cpp.i
.PHONY : VAO.i

# target to preprocess a source file
VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/VAO.cpp.i
.PHONY : VAO.cpp.i

VAO.s: VAO.cpp.s
.PHONY : VAO.s

# target to generate assembly for a file
VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/VAO.cpp.s
.PHONY : VAO.cpp.s

VBO.o: VBO.cpp.o
.PHONY : VBO.o

# target to build an object file
VBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/VBO.cpp.o
.PHONY : VBO.cpp.o

VBO.i: VBO.cpp.i
.PHONY : VBO.i

# target to preprocess a source file
VBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/VBO.cpp.i
.PHONY : VBO.cpp.i

VBO.s: VBO.cpp.s
.PHONY : VBO.s

# target to generate assembly for a file
VBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/VBO.cpp.s
.PHONY : VBO.cpp.s

calculateRays.o: calculateRays.cpp.o
.PHONY : calculateRays.o

# target to build an object file
calculateRays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/calculateRays.cpp.o
.PHONY : calculateRays.cpp.o

calculateRays.i: calculateRays.cpp.i
.PHONY : calculateRays.i

# target to preprocess a source file
calculateRays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/calculateRays.cpp.i
.PHONY : calculateRays.cpp.i

calculateRays.s: calculateRays.cpp.s
.PHONY : calculateRays.s

# target to generate assembly for a file
calculateRays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/calculateRays.cpp.s
.PHONY : calculateRays.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

shaderClass.o: shaderClass.cpp.o
.PHONY : shaderClass.o

# target to build an object file
shaderClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shaderClass.cpp.o
.PHONY : shaderClass.cpp.o

shaderClass.i: shaderClass.cpp.i
.PHONY : shaderClass.i

# target to preprocess a source file
shaderClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shaderClass.cpp.i
.PHONY : shaderClass.cpp.i

shaderClass.s: shaderClass.cpp.s
.PHONY : shaderClass.s

# target to generate assembly for a file
shaderClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shaderClass.cpp.s
.PHONY : shaderClass.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... EBO.o"
	@echo "... EBO.i"
	@echo "... EBO.s"
	@echo "... IBO.o"
	@echo "... IBO.i"
	@echo "... IBO.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... ModelLoader.o"
	@echo "... ModelLoader.i"
	@echo "... ModelLoader.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... VAO.o"
	@echo "... VAO.i"
	@echo "... VAO.s"
	@echo "... VBO.o"
	@echo "... VBO.i"
	@echo "... VBO.s"
	@echo "... calculateRays.o"
	@echo "... calculateRays.i"
	@echo "... calculateRays.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... shaderClass.o"
	@echo "... shaderClass.i"
	@echo "... shaderClass.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

